### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by o1dnik** [moberries/web-components#1]

**Comment by dimonnwc3** [comment]
Button

- [ ] bug with xlarge - it has diffirent color, should be the same
- [ ] css for spinner should be changed (discuss) [example](http://react.semantic-ui.com/elements/button#loading)
- [ ] needs diffirent positions to allign button, left, right, center
- [ ] needs base buttons w/o filling, basic class [example](http://react.semantic-ui.com/elements/button#basic)
- [ ] color and button type(basic) should not conflict together and can be combined

**Comment by o1dnik** [comment]
@hypersnob 
the functional side is finished, so you can do the styling (especialy `xlarge`  with styling like for Linkedin button)

**Comment by dimonnwc3** [comment]
Button

Button will be rendered as <button> tag
A button can have inside not only text, other elements as well:
e.g icon, or spinner

Default class: button

Color classes:

See HEX colors in Zeppelin style guide

button-primary - (black color)
button-default - (white/gray color)
button-success (green color)
button-danger (red color)
button-fb - facebook color
button-tw - twitter color

Outline class:

button-outline - with this class button should be not filled but should have a border with the same color
      without this class button should be filled, the default state

Extended class:
button-extended - button should take the full width

Sizes classes:

this set sizes of button

button-mini
button-tiny
button-small
button-medium
button-large
button-big
button-huge
button-massive

Disabled class:
button-disabled: button should be disabled
warning: this will add disabled attr on the element as well

Loading class:
button-loading: button should have loaded state, e.g spinner inside
Loader will be rendered inside button as first element <svg> with size tiny

Link class:
button-link: with this class button will be rendered as <a> tag and href attribute

**Comment by o1dnik** [comment]
Looks like the buttons are finished.
