### ISSUE TITLE
Box

### ISSUE THREAD

**Issue by o1dnik** [moberries/web-components#15]

**Comment by o1dnik** [comment]
https://github.com/moberries/web-components/commit/f3b48e5f969ba5bf8309c02a612c1d4c4d40db95

**Comment by samihda** [comment]
Box component for layout and renders children:

- [ ] wraps a parent `div` element with the class name "form-box"
- [ ] contains `fieldset` inner wrapper element with the class name "form-inner"
- props:
children (required)
