### ISSUE TITLE
Tag & Tags Style/css

### ISSUE THREAD

**Issue by o1dnik** [moberries/web-components#24]

**Comment by dimonnwc3** [comment]
Tag

Tag will be rendered as span tag

A tag can have inside not only text, other elements as well:
e.g icon

Default class: tag

Classes can be combined without conflicts

Color classes:

See HEX colors in Zeppelin style guide

class tag-default - grey color
class tag-primary - green color
class tag-danger - orange color
class tag-light - light grey color

Bordered class:
tag-bordered - tag have a border, a little bit darker as tag color, see design

Extended class:
tag-extended - tag should take the full width

Sizes classes:

this set sizes of tag

tag-xsmall
tag-small
tag-medium
tag-large
tag-xlarge

With icon:
tag-icon class

icon can be placed right or left from text, or without text


Clickable class
tag-clickable - add cursour pointer

**Comment by o1dnik** [comment]
https://github.com/moberries/web-components/commit/29cf30c6a854070b86be1de56a008e52340c5066, https://github.com/moberries/web-components/commit/3589e034acb0863cbfcf3b9284735eda2dfc8aa1
