### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by o1dnik** [moberries/web-components#5]

**Comment by dimonnwc3** [comment]
we need styles for it.
input has 3 states

- [ ] default
it has only input class

- [ ] success
it has input and input-success class.
with input-success class it should be green

- [ ] error
it has input and input-error class.
with input-error class it should be red
as well we should see red error message below in span element

**Comment by o1dnik** [comment]
@hypersnob 
the functional side is finished, waiting for styling
