### ISSUE TITLE
LinkButton

### ISSUE THREAD

**Issue by o1dnik** [moberries/web-components#6]

**Comment by dimonnwc3** [comment]
@o1dnik do we really need this?

**Comment by o1dnik** [comment]
Actually I do not think so. The motivation was to make an &lt;a&gt; and &lt;button&gt; or &lt;div&gt; with classname `button` to look and feel. But we should do that by convention in a single way. As an example we have to check for `href` prop like in React-Bootstrap Button https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Button.js#L66

**Comment by dimonnwc3** [comment]
we can try to add 'as' prop to Button, what takes string (tagname) or component, and renders instead of button <a>, or <Link> for example

**Comment by dimonnwc3** [comment]
will be done as a tag in Button component if href #1
